unique_ids:
  assets:
    standard-page.html: LYMYH7B56BYWDRPUUXIV5LAJCKK3ERK7
    theme.css: HTG4Q4QAOA2NJ77MZMITGBDWC4WPN3O6
  forms:
    Form1: NZUDNZSGFGE6R7YNGOB36HYDZAHFBGYK
  modules: {}
  scripts: {}
  server_modules: {}
